### ISSUE TITLE
map.neighbors() sometimes does not return accesible tiles.

### ISSUE THREAD

**Issue by BezPowell** [THeK3nger/movingai-rust#7]
In certain very rare circumstances the map.neighbors() function does not return all accessible neighbours of the given tile. I've been testing this using the maze512-32-9.map.scen file and it works correctly for all but five of the over 8000 scenarios, however, using the neighbors function for the starting node on those 5 scenarios means the algorithm fails to find a path.

Scenario number 1740 is the first where this fails. The Start tile is (462, 331) and goal tile is (105, 129)

```
map.neighbors() returns:
(463, 331)
(463, 332)
(462, 332)
(461, 331)
(461, 332)
```

```
Whereas checking each neighbouring tile with map.is_traversable() returns:
(461, 331)
(461, 332)
(462, 332)
(463, 330)
(463, 331)
(463, 332)
```
I've attached the relevant .map and .scen file here:
[maze512-32-9.zip](https://github.com/THeK3nger/movingai-rust/files/4948015/maze512-32-9.zip)

**Comment by THeK3nger** [comment]
Thank you very much for your detailed report. It is a very unfortunate bug. I created a test for this specific case and I'll work on a fix soon. Sorry for the huge delay.

**Comment by THeK3nger** [comment]
I am not sure that's the problem though. The fact that `neighbors` and `is_traversable` are different is correct. In fact, your example is a corner tile (the `x` is the starting position)

```
@..
@x.
...
```

We have 6 traversable tiles, however, I cannot reach the tile marked with `#` from `x`.

```
@..
@x.
#..
```

Because the [format specifications](https://movingai.com/benchmarks/formats.html) state that:

> The optimal path length assumes agents **cannot cut corners through walls**

Therefore, when I return the list of the traversable tiles _from `x`_, I need to exclude that one (in your example, the `(463, 330)` tile. 

However, if the scene fails, it is indeed a problem. I'll investigate more and keep this bug issue updated.
